### ISSUE TITLE
maps doesn't appear

### ISSUE THREAD

**Issue by maroulu** [tomtom-international/tomtom-use-case-search-along-a-route-android#3]
i am trying the demo app but the map layer doesn't appear
it shows only a white screen instead of the map

**Comment by szczepanczyk** [comment]
Hi @maroulu ! 
Please make sure that you are using a valid API key inside AndroidManifest.xml file like it is described here: https://developer.tomtom.com/maps-sdk-android/android-tutorials-use-cases/search-along-route#prerequisites
