### ISSUE TITLE
get arrival time of a route

### ISSUE THREAD

**Issue by maroulu** [tomtom-international/tomtom-use-case-search-along-a-route-android#4]
hello please i create a route with a depart time can i get the arrival time?
and is there a way to get the way point of a route set with only a departure and arrival coo.

**Comment by szczepanczyk** [comment]
Hi. 
You can take arrival time from from RouteResult object: routeResult.routes[0].summary.arrivalTime. Regarding way point, I'm not sure whether I fully understand your needs, but I think that you can try to get it from routeResult.getRoutes().get(0).getLegs() method.
